### ISSUE TITLE
Write EDA Notebook based on available Sippy Data. 

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#13]
Beyond the failure correlations already started, there may be other features in the sippy data that could be used for additional analysis. In order to do our data science due diligence, we will create a notebook going through this dataset.

**Comment by durandom** [comment]
I just merged your WIP PR, I think it's as good as we can get with sippy data.
Did you actually use sippy and load some of it's reports? My guess is they're similar to what we have in the EDA notebook now. Since sippy already tries to do some reporting, I think we should move on to the actual ground truth: testgrid.

**Comment by MichaelClifford** [comment]
@durandom yes, I used sippy to pull a report json for the analysis. Sippy allows us to pull data reports directly, and also displays the data in html [here](https://sippy.ci.openshift.org/?release=4.6). You can see how their reports differ from what's in the EDA notebook, But you are right they are similar in underlying content (as its the same data :smile: ) 

But I think overall you are right, other than finding the test failure correlations and identifying the jobs and tests that are failing most, sippy (at least as I understand it now) doesn't provided us access to the underlying data needed for some automated root cause analysis we are ultimately aiming for.
