### ISSUE TITLE
Data source: GitHub

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#146]
In addition the testgrid data (which is ultimately a higher order signal telling us which of a set of tests passed or failed during a CI run) we want to be able to include the associated PR's and code changes underlying the CI runs to provide more in-depth analysis and ideally support automated root cause analysis. 

We currently have no tooling in place to trace the code changes made between CI runs displayed on Testgrid.  

Write a notebook that, given a specific build/CI run from testgrid, returns the associated PR or set of PR's from github. 

**Acceptance Criteria**

 - [x] Notebooks for collecting links to PR's from testgrid data.
- [x] Small sample data set available in repo

**Comment by pacospace** [comment]
There is an existing component able to extract metadata from github repos [1].

In order to create a sample dataset:

- [ ] verify the Meta-information Indicators available are sufficient for you: https://github.com/thoth-station/mi/tree/master/srcopsmetrics/entities#meta-information-indicators-metrics, otherwise please open a feature request in [1].
- [ ] provide a list of repos that needs to be analyzed, opening a PR in https://github.com/thoth-station/thoth-application/blob/014ce6cec37645237cfd62ed8303ac62ceb57ed1/mi-scheduler/base/configmaps.yaml#L7

[1] https://github.com/thoth-station/mi

cc @xtuchyna

**Comment by MichaelClifford** [comment]
@pacospace @xtuchyna this sounds like a rather restrictive way of accessing GitHub data, at least from a data exploration and ML prototyping point of view. Ideally we would want a dataset that that collected all closed PR's from [openshift orgin](https://github.com/openshift/origin) including their written description, author(s), number of files, file types, etc.  in addition to the diff. We could then develop features from this data and use it to attempt and predict some of the meta-information indicators you are already collecting.   

Correct me if I'm misunderstanding the purpose of the MI project, but it looks like it controls a bot that analyzes repos and then returns some stats about them. If this is the case, would it make sense for our team to work on developing some predictive models on the github data that can then be contributed back  and integrated into the MI project? Adding things like "predicted time to merge" to list of Meta-information Indicators Metrics?
