### ISSUE TITLE
KPI Request: Percent of Failing Tests Fixed

### ISSUE THREAD

**Issue by chauhankaranraj** [aicoe-aiops/ocp-ci-analysis#149]
As an OpenShift manager, I want to know what percent of tests that were failing in the previous test run got fixed in the current test run. This information can potentially help me quantify the agility and efficiency of our team.

If this number is higher, it means we were able to quickly identify the root causes of all failing tests in the previous run and fix them. Conversely if this number is low, meaning only a small percent of previously failing tests get fixed in each new run, then our CI process is likely not as efficient as it could be.

**Acceptance criteria**
- [x] small notebook in `notebooks/data-sources/TestGrid/metrics/` that collects this metric and stores it in ceph as a parquet

**Comment by chauhankaranraj** [comment]
The notebook added in #122 contains some relevant analysis, so it can just be repurposed for this KPI calculation

**Comment by aakankshaduggal** [comment]
In order to know what percent of tests that were failing in the previous test run got fixed in the current test run we could have three scenarios : 
* **Calculate the tests failed** : 
(Total number of tests failed in *nth* iteration - Total number of tests failed in *(n-1)th* iteration) / Total number of Tests
* **Calculate only the tests changing from fail to pass** : In this situation, we will only look for tests that were red[fail] in the *(n-1)th* interaction and then changed to green in *nth* iteration. i.e. 
(Total number of tests failed in *nth* iteration that also failed in *(n-1)th* iteration - Total number of tests failed in *(n-1)th* iteration) / Total number of Tests
* **Calculate the tests that changed from pass to fail** : In this situation, we will look for tests that were green[pass] in the *(n-1)th* iteration but changed to red[fail] in the *nth* iteration. i.e. 
 (Total number of tests failed in *nth* iteration that passed in *(n-1)th* iteration - Total number of tests failed in *(n-1)th* iteration) / Total number of Tests


cc : @Shreyanand @chauhankaranraj

**Comment by MichaelClifford** [comment]
I think something like option 2 is the way to go here. If you take only the tests in run n-1 that failed, then determine the number of those that changed to "pass" and divide that by the total number of failures in run n-1, then you'll have a value for the percent of failing tests fixed between each CI run for a grid. These values could then be plotted as a time series, or aggregated into monthly averages or something. But I think calculating this value per grid between consecutive builds (test grid columns) makes sense. WDYT?

**Comment by chauhankaranraj** [comment]
> I think something like option 2 is the way to go here.

Yep makes sense! That's what we were initially inclining towards too. Just wanted to make sure our understanding of the KPI definition is correct :)

**Comment by chauhankaranraj** [comment]
**NOTE**: In the notebook (see #153) which solves this issue, we were initially trying to do a relatively "complex" `groupby` and then aggregate its results to calculate this KPI. However, doing that caused the kernel to crash every time (for an 8GB memory JH pod). So we had pivoted to manually updating the function that parses the json data into a dataframe, and explicitly calculate this metric.

That said, if we had more than 8GB memory, then this notebook could have been made more succinct (although not as much memory-efficient) and would have saved us some debugging time. So going forward, we should probably request a larger memory profile on MOC JH so we can quickly create such notebooks.

cc @aakankshaduggal @Shreyanand
