### ISSUE TITLE
Timestamp and Label do not match in test_pass_failure and number_of_flakes nb

### ISSUE THREAD

**Issue by oindrillac** [aicoe-aiops/ocp-ci-analysis#165]
**Describe the bug**
In the dataframe exported after the `testgrid_labelwise_encoding` step in the test_pass_failure and number_of_flakes notebook, the timestamp do not seem to reflect what is on the dashboard.

Following are screenshots of the dataframe and testgrid from the same date. As seen, for the test "overall" , although the pass/fail pattern seems to be same as the dashboard, the timestamps in the dataframe for the pass/fail labels do not match that in the testgrid UI. 

**Dashboard**

![date-issue-1](https://user-images.githubusercontent.com/32435206/111316264-7e96c500-8639-11eb-99b3-e79c636c6b92.png)

**Notebook**

![date-issue-2](https://user-images.githubusercontent.com/32435206/111316273-80608880-8639-11eb-81b1-5a90cffd6e9c.png)

**To Reproduce**
1. Go to 'testgrid_EDA' notebook and download dataset for the latest day by running section 1.2 and make `https://testgrid.k8s.io/{dashboard}/table?&show-stale-tests=&tab={job}&grid=old` to `https://testgrid.k8s.io/{dashboard}/table?&show-stale-tests=&tab={job}` to get latest date in following lines:
```
for job in jobs:
            response_2 = requests.get(
                f"https://testgrid.k8s.io/{dashboard}/table?&show-stale-tests=&tab={job}&grid=old"
            )
```
2. Dataset is saved as testgrid_163.json.gz
3. Read dataset in "test_pass_failure" notebook and run cells
4. Inspect dataframe by `failures_df.head()`
5. Compare with latest dashboard on testgrid UI : https://testgrid.k8s.io/redhat-openshift-informing#release-openshift-okd-installer-e2e-aws-upgrade

**Expected behavior**
The timestamps in the dataframe are supposed to reflect that of the UI.
Although the pattern, pass/fail seems to exactly reflect that in the UI, the timestamps seem to be phase shifted.

**Comment by MichaelClifford** [comment]
@oindrillac how much is the time shifted by? This might just be an issue of not setting the ` datetime.datetime.fromtimestamp` to EDT.

**Comment by oindrillac** [comment]
@MichaelClifford it seems to be shifted by 2 records here

**Comment by MichaelClifford** [comment]
Based on the two images below, that were taken seconds apart, we can see that the web UI can render the timestamps based either on local time or not local time. 

![image](https://user-images.githubusercontent.com/4494906/111327184-89565780-8643-11eb-8f58-70394e7a947e.png)
![image](https://user-images.githubusercontent.com/4494906/111327258-9c692780-8643-11eb-89f5-b1f711d35caa.png)


Since we are just making a call to `datetime.datetime.fromtimestamp()` on an epoch timestamp in the underlying data in both of these notebooks, the date time might not match exactly, but if you look at the values in the minutes column you can see that the timestamps are shifted by complete hours, indicating that its simply due to a timezone conversion issue.   

It might make sense to add a timezone option in these notebooks so that users can convert their outputs into ones that will match up with their local timezones when comparing to a testgrid dashboard.
