### ISSUE TITLE
Pipenv Install Errors Out

### ISSUE THREAD

**Issue by chauhankaranraj** [aicoe-aiops/ocp-ci-analysis#197]
**Describe the bug**
Pipenv throws errors while installing the requirements on MOC JH. This results in packages not installing correctly and thus the notebooks also don't run.

**To Reproduce**
1. Go to https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud
2. Spawn an `s2i-minimal` notebook image
3. `git clone` this repo and `cd` into it
4. Run `pipenv install`
5. See error

**Expected behavior**
Requirements get installed.

**Screenshots**
![install-error](https://user-images.githubusercontent.com/15005500/112676588-fbe2e680-8e3e-11eb-87e6-983c14edddc2.png)

**Additional context**
Could this have something to do with the recent Pipfile change where python was updated to 3.8?

**Comment by oindrillac** [comment]
@chauhankaranraj yes i think its probably the python version which is 3.6 here and the project is 3.8

**Comment by hemajv** [comment]
@chauhankaranraj yep seems like ipython 17.21.0 requires `python>=3.7`: https://pypi.org/project/ipython/

**Comment by chauhankaranraj** [comment]
Yeah so for now I've installed `pyenv` on my JH instance and set it to use python version `3.8.0` for this project. This probably is not a long term solution, but if anyone's looking for a temporary workaround, this should work fine :smiley:

**Comment by MichaelClifford** [comment]
Thanks @chauhankaranraj. I think this is an issue for the Thoth team to upgrade the available images to 3.8.  Another thing that could help fix this issue is some better documentation about what's contained in each of the images (there is this [PR](https://github.com/operate-first/support/issues/162)), so that you don't use a 3.7 image for a project that requires 3.8. 

Instead of using pyenv, you could use one of the lab images which have 3.8 installed as well.
