### ISSUE TITLE
Revisit Test Grid Failure Type Analysis

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#274]
One of the original analytics projects that we had outlined for this project was "Failure Type Classification". It was partially completed awhile back and exists in `notebooks/failure-type-classification/stage/failure_type_classifier.ipynb`. This project  should be picked back up and polished. 

Acceptance Criteria:
- [ ] Review and polish existing notebook. 
- [ ] Notebook run continuously as part of a pipeline to collect results and store in Ceph.    
- [ ] Video Demo and Walkthrough

**Comment by isabelizimm** [comment]
Is the "Evaluation if this notebook can be improved with the additional data collected recently." criteria referring to additional TestGrid data or adding in different data sources?

**Comment by MichaelClifford** [comment]
@isabelizimm it is referring to the different data sources

**Comment by Shreyanand** [comment]
Logs seem like a good starting place for this. We could look at the failing tests' logs and see if they have some information about the type of failure. 
@MichaelClifford we don't really have a good understanding of this, so a couple of questions:

1. The annotated image seems like a good example (from 23-29 March), but correct us if we're wrong, the output at the end are from a different time (Sept-Oct). I think it would make more sense to have the methods detect the types of flakes from the same time as the image unless there was something stopping us, was there? Also, Is there any SME we know who labelled this? Is there a way to get more examples? It will help us validate the models better. 

2. Are there telemetry metrics that can indicate some of these failures? It seems like there are a lot of metrics highlighted in the telemetry_EDA.ipynb but no way of knowing what would be relevant for failure type classification. Do SMEs look at metrics to find what kind of failure it is? Or do they just look at the patterns like annotated in the image?

3. Just to confirm, the overall goal here is to reduce the response time of solving a failure by making sure that developers don't have to waste time trying to figure out flaky fails? Do we have an approximation on how prevalent this problem is in terms of man hours spent trying to solve this?

cc @isabelizimm

**Comment by MichaelClifford** [comment]
> The annotated image seems like a good example (from 23-29 March), but correct us if we're wrong, the output at the end are from a different time (Sept-Oct). I think it would make more sense to have the methods detect the types of flakes from the same time as the image unless there was something stopping us, was there? 

I don't think the data was retained  far enough to go back to the original image. But you should check. Yes, evaluating the methods on the same time frame is a good check. But we also want to show that it can perform on new time periods as well.  

 > Also, Is there any SME we know who labelled this? Is there a way to get more examples? It will help us validate the models better.

https://github.com/aicoe-aiops/ocp-ci-analysis/issues/1 see these comments on the annotations, I believe these were made by Clayton Colman. 

>Are there telemetry metrics that can indicate some of these failures? 

Probably, but we don't currently know what they are. This is something that could potentially be investigated as part of this work. But, I would imagine that you would need to apply the heuristics here first to find potentially problematic builds before looking at how the errors are reflected in the telemetry metrics. So maybe the telemetry data does not need to be included right now.     

>Do we have an approximation on how prevalent this problem is in terms of man hours spent trying to solve this?

No.

The goal here is to encode the subject matter expert's knowledge into an automated process so that evaluating a test grid does not have to be done manually.  


The acceptance criteria "Evaluation if this notebook can be improved with the additional data collected recently" should not be exhaustive. I just want to make sure we don't ignore an obvious addition now that we know more about the entire CI data set.

**Comment by Shreyanand** [comment]
> > The annotated image seems like a good example (from 23-29 March), but correct us if we're wrong, the output at the end are from a different time (Sept-Oct). I think it would make more sense to have the methods detect the types of flakes from the same time as the image unless there was something stopping us, was there?
> 
> I don't think the data was retained far enough to go back to the original image. But you should check. Yes, evaluating the methods on the same time frame is a good check. But we also want to show that it can perform on new time periods as well.
> 
Thanks, will check that out. The idea was to be able to numerically validate existing methods with at least one example. Showing that it works on new data should follow without any problem. 


> > Also, Is there any SME we know who labelled this? Is there a way to get more examples? It will help us validate the models better.
> 
> #1 see these comments on the annotations, I believe these were made by Clayton Colman.
> 
> > Are there telemetry metrics that can indicate some of these failures?
> 
> Probably, but we don't currently know what they are. This is something that could potentially be investigated as part of this work. But, I would imagine that you would need to apply the heuristics here first to find potentially problematic builds before looking at how the errors are reflected in the telemetry metrics. So maybe the telemetry data does not need to be included right now.
> 
> > Do we have an approximation on how prevalent this problem is in terms of man hours spent trying to solve this?
> 
> No.
> 
The reason for asking this was to ensure that we understand the gravity of the requirement. Maybe it's a nice add-on, maybe it's a life saving feature, or somewhere in between.

> The goal here is to encode the subject matter expert's knowledge into an automated process so that evaluating a test grid does not have to be done manually.
> 
> The acceptance criteria "Evaluation if this notebook can be improved with the additional data collected recently" should not be exhaustive. I just want to make sure we don't ignore an obvious addition now that we know more about the entire CI data set.

Thanks for linking the issue, it's very helpful. Do you think in order to encode the subject matter expert's knowledge into an automated process, we should reach out to them and ask about all the data sources they use to classify a failure? Do they look at logs, Bugzilla, or metrics? In one case he mentions the reason for failure as "someone force merged". This information could be there in the Github data... Or it could be that they are just look at the patterns as mentioned in the issue that you shared. In that case we validate on some examples and improve existing methods.

**Comment by MichaelClifford** [comment]
> Do you think in order to encode the subject matter expert's knowledge into an automated process, we should reach out to them and ask about all the data sources they use to classify a failure? 

No. I think that we should take the information that we have now from the existing notebook, the comment and the annotated image and implement the best solution we can at the moment as part of an automated pipeline. Once we have a working prototype, we should share it with SME's for feedback to see how we can expand and improve upon it.
