### ISSUE TITLE
Implement approach from build_log_term_freq.ipynb into deployable service

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#305]
Now that the experimental work from `notebooks/data-sources/gcsweb-ci/build-logs/build_log_term_freq.ipynb` has been completed, and shown to be a promising approach, let's implement it as a service so that it can actually be used.

**Comment by MichaelClifford** [comment]
cc @codificat

**Comment by isabelizimm** [comment]
Will be tracking steps/outline [here](https://docs.google.com/document/d/1lFTcHhawvVYPSY2lnLpImSeVHQp7fD_yKhtYM8tobD4/edit?usp=sharing) so others are able to follow for their own Seldon deployments

**Comment by isabelizimm** [comment]
After looking further into this, we have found a few places which makes this deployment more complex than originally anticipated:

- The SKLearn Seldon deployment requires a `predict` function, and tfidf has `transform`
- The notebook trains the tfidf model using input="filename" which makes a file, not a string, the expected input. We have to figure out the feasibility of posting files, or, otherwise creating a new model that ingests strings.

**Comment by codificat** [comment]
>     * The SKLearn Seldon deployment requires a `predict` function, and tfidf has `transform`

Wouldn't we be calling `predict` on the clustering model (k-means) instead? with tf-idf vectors as input though...

>     * The notebook trains the tfidf model using input="filename" which makes a file, not a string, the expected input. We have to figure out the feasibility of posting files, or, otherwise creating a new model that ingests strings.

Loading in memory might work with tf-idf, depending on resources and dataset (some of these log files can be relatively big). It will most likely not work with doc2vec though.
