### ISSUE TITLE
Relative link for readme.md file in project-doc.md

### ISSUE THREAD

**Issue by SankBad** [aicoe-aiops/ocp-ci-analysis#50]
**Is your feature request related to a problem? Please describe.**
Currently, we have a copy `readme.md` file inside `docs/publish/project-doc.md`
Hence, whenever we are updating readme.md file we need to update `docs/publish/project-doc.md`

**Describe the solution you'd like**
We can use [relative link](https://stackoverflow.com/questions/7653483/github-relative-link-in-markdown-file) in one of the Markdown files to avoid two different copy of the same file.

**Acceptance criteria**
relative link of  `readme.md` file in `docs/publish/project-doc.md`

**Comment by SankBad** [comment]
Hi @MichaelClifford , 
Is this sound good?

**Comment by MichaelClifford** [comment]
Hey @SankBad Thanks for creating this issue :smile: . I am aware of the current duplicate README/project-doc content. That said, as the project evolves, I am assuming that the initial project doc and the repo readme will start to diverge in content, so this might be ok. 

That said, since they are currently the same, it would be nice if they were linked in some way. Does the "relative" link solution you've suggested actually render the content? or does it just allow you to create a link with the files relative path in the repo instead of the absolute github path?

**Comment by SankBad** [comment]
@MichaelClifford , 

Good point. actually, it just allows you to create a link with the file's relative path in the repo instead of the absolute GitHub path. 

That being said, it seems like the feature we want is not available at the moment. There are several discussions about this feature on GitHub repo but it never implemented due to different reasons. 

Discussion1 [Link](https://github.com/isaacs/github/issues/471)
Discussion2 [Link](https://github.com/github/markup/issues/172)

**Comment by SankBad** [comment]
So, Marcel removed the file from the doc folder. We are using readme.md for operate first website.
This issue is no longer relevant. I am closing this issue.
